---
name: Apply
on:
  push:
    branches:
      - main

env:
  SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}

jobs:
  deploy:
    runs-on: arc-dind
    container: registry.docker-registry.svc:5000/makeitworkcloud/terraform-runner:latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Git as root
        run: git config --global --add safe.directory '*'

      - name: Terraform apply
        run: make apply
